#!/bin/bash

cd  /netshare1/home1/szzhongxin/proj1/hansun/Viruses/mapping2/10A

bwa aln -I  \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruse \
/netshare1/home1/szzhongxin/proj1/fudan2/10A/D-M10A_w4q20m35_N_1.fq \
>10A.D-M10A_w4q20m35_N_1.sai

bwa aln -I  \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruse \
/netshare1/home1/szzhongxin/proj1/fudan2/10A/D-M10A_w4q20m35_N_2.fq \
>10A.D-M10A_w4q20m35_N_2.sai


bwa sampe  \
/netshare1/home1/szzhongxin/proj1/hansun/Viruses/bwa/hg19viruse \
10A.D-M10A_w4q20m35_N_1.sai \
10A.D-M10A_w4q20m35_N_2.sai \
/netshare1/home1/szzhongxin/proj1/fudan2/10A/D-M10A_w4q20m35_N_1.fq \
/netshare1/home1/szzhongxin/proj1/fudan2/10A/D-M10A_w4q20m35_N_2.fq \
-r "@RG\tID:m10a\tSM:m10a\tLB:m10a\tPL:illumina\tPU:barcode" | \
samtools view -bS -o 10A.D-M10A_w4q20m35_N.bam -

samtools  sort 10A.D-M10A_w4q20m35_N.bam 10A.D-M10A_w4q20m35_N.sorted

