#qsub varScan.icc9.chr10.sh -l nodes=n4 -q high 
#qsub varScan.icc9.chr11.sh -l nodes=n5 -q high 
#qsub varScan.icc9.chr12.sh -l nodes=n6 -q high 
#qsub varScan.icc9.chr13.sh -l nodes=n7 -q high 
#qsub varScan.icc9.chr14.sh -l nodes=n9 -q high 
#qsub varScan.icc9.chr15.sh -l nodes=n10 -q high 
#qsub varScan.icc9.chr16.sh -l nodes=n11 -q high 
#qsub varScan.icc9.chr17.sh -l nodes=n12 -q high 
#qsub varScan.icc9.chr18.sh -l nodes=n13 -q high 
#qsub varScan.icc9.chr19.sh -l nodes=n14 -q high 
#qsub varScan.icc9.chr1.sh -l nodes=n15 -q high 
#qsub varScan.icc9.chr20.sh -l nodes=n16 -q high 
#qsub varScan.icc9.chr21.sh -l nodes=n17 -q high 
#qsub varScan.icc9.chr22.sh -l nodes=n19 -q high 
#qsub varScan.icc9.chr2.sh -l nodes=n21 -q high 
#qsub varScan.icc9.chr3.sh -l nodes=n22 -q high 
qsub varScan.icc9.chr4.sh -l nodes=cu01  
qsub varScan.icc9.chr5.sh -l nodes=cu02  
qsub varScan.icc9.chr6.sh -l nodes=cu03 
qsub varScan.icc9.chr7.sh -l nodes=cu04 
qsub varScan.icc9.chr8.sh -l nodes=cu05 
qsub varScan.icc9.chr9.sh -l nodes=cu06 
qsub varScan.icc9.chrX.sh -l nodes=cu07 
qsub varScan.icc9.chrY.sh -l nodes=cu08 
